# Generated by Django 2.1.7 on 2019-03-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('position', models.CharField(max_length=100)),
                ('dscp', models.CharField(max_length=200)),
                ('imglink', models.CharField(max_length=100)),
                ('taken', models.BinaryField()),
                ('lof', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SortObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Object')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.AllSort')),
            ],
        ),
        migrations.CreateModel(
            name='TakenRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('lof', models.BinaryField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Object')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('ifadmin', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User')),
            ],
        ),
        migrations.AddField(
            model_name='takenrecord',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to='model.User'),
        ),
        migrations.AddField(
            model_name='takenrecord',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to='model.User'),
        ),
    ]
