# Generated by Django 2.1.7 on 2019-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='imglink',
        ),
        migrations.RemoveField(
            model_name='object',
            name='lof',
        ),
        migrations.RemoveField(
            model_name='object',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='takenrecord',
            name='lof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifadmin',
        ),
        migrations.AddField(
            model_name='object',
            name='img',
            field=models.ImageField(default='Object', upload_to=''),
        ),
        migrations.AddField(
            model_name='object',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takenrecord',
            name='tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.BooleanField(default=False),
        ),
    ]
