# Generated by Django 2.1.7 on 2019-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20190312_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.ImageField(default='default/default.jpg', upload_to='img/object'),
        ),
    ]
