# Generated by Django 2.1.7 on 2019-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20190312_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='time',
            field=models.DateField(),
        ),
    ]
