# Generated by Django 2.1.7 on 2019-03-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20190313_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='psw',
            new_name='pwd',
        ),
    ]
