# Generated by Django 2.1.7 on 2019-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20190314_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.ImageField(upload_to='img/object'),
        ),
    ]
