# Generated by Django 2.1.7 on 2019-03-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20190314_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='state',
            field=models.IntegerField(),
        ),
    ]
