# Generated by Django 2.1.7 on 2019-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20190316_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
