# Generated by Django 2.1.7 on 2019-03-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20190317_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobject',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
